### ISSUE TITLE
WSLink examples are broken.

### ISSUE THREAD

**Issue by ajain-work** [Kitware/wslink#156]
**Describe the bug**

After introducing msgpack+chunking in [PR](https://github.com/Kitware/wslink/pull/153) C++ [example ](https://github.com/Kitware/wslink/tree/master/cpp) is not working.

**To Reproduce**

Please try to run [example ](https://github.com/Kitware/wslink/tree/master/cpp)

***Code***

Please check code [here](https://github.com/Kitware/wslink/blob/95202796da9980dbe6d7d1a1c79216d859558b94/cpp/wsWebsocketConnection.h#L305C2-L311C49)

Json data is sent instead of binary.

**Expected behavior**

 [example ](https://github.com/Kitware/wslink/tree/master/cpp) should work.

**Platform:**

Linux

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [ ] MacOS
- [x] Linux
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] IE (Version)

***wslink version:***
vMAJOR.MINOR.PATCH

**Comment by jourdain** [comment]
Good catch, let me remove it from the repo since it is only compatible with wslink<2

**Comment by ajain-work** [comment]
Hi @jourdain, I think it will be good if you can fix the examples instead of removing them. Example are helpful to user. Regards

**Comment by jourdain** [comment]
By removing, I'm not talking about the example but the full C++ implementation (Already done). Especially since it does not make sense to keep maintaining a feature that is not used. But if a customer does request the support, it will be easy to revive and update the code. Right now, we don't have funding to maintain that C++ side, so it is easier to remove it to prevent miss usage. 

Keep in mind, that it still possible to use wslink<2 in C++ as a client.

Hope that make sense
